"use client";

import { nanoid } from "nanoid";
import { Product } from "./columns";
import {
	MdInventory,
	MdBuild,
	MdPhoneIphone,
	MdLaptop,
	MdKitchen,
	MdHome,
	MdChair,
	MdLightbulbCircle,
	MdOutlineDoorSliding,
} from "react-icons/md";
import { FaHeadphones } from "react-icons/fa";

export const products: Product[] = [
	{
		id: nanoid(),
		name: "Wrench",
		supplier: "ToolSupplier Inc.",
		sku: "WR101",
		category: "Others",
		status: "Draft",
		quantityInStock: 40,
		price: 10.99,
		icon: <MdBuild />,
		createdAt: new Date("2023-01-15"),
	},
	{
		id: nanoid(),
		name: "Nail Gun",
		supplier: "ToolSupplier Inc.",
		sku: "NG202",
		category: "Others",
		status: "Published",
		quantityInStock: 25,
		price: 45.99,
		icon: <MdInventory />,
		createdAt: new Date("2023-02-10"),
	},
	{
		id: nanoid(),
		name: "Smartphone Pro",
		supplier: "TechWorld",
		sku: "SP303",
		category: "Electronics",
		status: "Published",
		quantityInStock: 75,
		price: 599.99,
		icon: <MdPhoneIphone />,
		createdAt: new Date("2023-03-05"),
	},
	{
		id: nanoid(),
		name: "Gaming Laptop",
		supplier: "TechWorld",
		sku: "GL404",
		category: "Electronics",
		status: "Inactive",
		quantityInStock: 30,
		price: 1200.99,
		icon: <MdLaptop />,
		createdAt: new Date("2023-04-20"),
	},
	{
		id: nanoid(),
		name: "Toaster",
		supplier: "HomeGoods Co.",
		sku: "TS505",
		category: "Home Appliances",
		status: "Draft",
		quantityInStock: 20,
		price: 39.99,
		icon: <MdKitchen />,
		createdAt: new Date("2023-05-18"),
	},
	{
		id: nanoid(),
		name: "Vacuum Cleaner",
		supplier: "HomeGoods Co.",
		sku: "VC606",
		category: "Home Decor",
		status: "Published",
		quantityInStock: 10,
		price: 150.0,
		icon: <MdHome />,
		createdAt: new Date("2023-06-22"),
	},
	{
		id: nanoid(),
		name: "Mini Fridge",
		supplier: "HomeGoods Co.",
		sku: "MF707",
		category: "Home Appliances",
		status: "Inactive",
		quantityInStock: 12,
		price: 249.99,
		icon: <MdKitchen />,
		createdAt: new Date("2023-07-10"),
	},
	{
		id: nanoid(),
		name: "Convertible Tablet",
		supplier: "TechWorld",
		sku: "CT808",
		category: "Electronics",
		status: "Draft",
		quantityInStock: 50,
		price: 349.99,
		icon: <MdLaptop />,
		createdAt: new Date("2023-08-15"),
	},
	{
		id: nanoid(),
		name: "Wireless Headphones",
		supplier: "AudioTech",
		sku: "WH909",
		category: "Electronics",
		status: "Published",
		quantityInStock: 45,
		price: 99.99,
		icon: <FaHeadphones />,
		createdAt: new Date("2023-09-01"),
	},
	{
		id: nanoid(),
		name: "Ergonomic Chair",
		supplier: "FurnitureGalore",
		sku: "EC010",
		category: "Furniture",
		status: "Inactive",
		quantityInStock: 15,
		price: 199.99,
		icon: <MdChair />,
		createdAt: new Date("2023-10-12"),
	},
	{
		id: nanoid(),
		name: "Desk Organizer Lamp",
		supplier: "HomeGoods Co.",
		sku: "DL111",
		category: "Electronics",
		status: "Draft",
		quantityInStock: 35,
		price: 29.99,
		icon: <MdLightbulbCircle />,
		createdAt: new Date("2023-11-05"),
	},
	{
		id: nanoid(),
		name: "Precision Gaming Mouse",
		supplier: "TechWorld",
		sku: "PGM212",
		category: "Electronics",
		status: "Published",
		quantityInStock: 60,
		price: 49.99,
		icon: <MdHome />,
		createdAt: new Date("2023-12-01"),
	},
	{
		id: nanoid(),
		name: "Rapid Electric Kettle",
		supplier: "HomeGoods Co.",
		sku: "REK313",
		category: "Home Appliances",
		status: "Draft",
		quantityInStock: 20,
		price: 59.99,
		icon: <MdKitchen />,
		createdAt: new Date("2024-01-08"),
	},
	{
		id: nanoid(),
		name: "BBQ Grill",
		supplier: "HomeDepot",
		sku: "BBQ414",
		category: "Furniture",
		status: "Published",
		quantityInStock: 10,
		price: 299.99,
		icon: <MdOutlineDoorSliding />,
		createdAt: new Date("2024-02-14"),
	},
];
